function createfigure(data1, X1, Y1)
%CREATEFIGURE(data1, X1, Y1)
%  DATA1:  histogram data
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 20-Jun-2018 21:40:12

% Create figure
figure1 = figure('Name','Tomography');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'DisplayName','Эксперимент','Parent',axes1,'FaceAlpha',1,...
    'EdgeColor',[0.0117647058823529 0.164705882352941 0.164705882352941],...
    'FaceColor',[0.0117647058823529, 0.325490196078431, 0.36078431372549],...
    'BinWidth',0.00031);

% Create text
text('Parent',axes1,'HorizontalAlignment','right','FontSize',16,...
    'FontName','Times New Roman',...
    'String','\rho = 0.5\mid0\rangle\langle0\mid+0.5\mid1\rangle\langle1\mid',...
    'Position',[0.00600906136620883 99.0947224413716 0]);

% Create text
text('Parent',axes1,'FontSize',16,'FontName','Times New Roman',...
    'String',{'','n = 10000, N_{exp} = 1000','t = 1.00, T_{1} = 1.00, T_{2} = 1.00'},...
    'Position',[0.00383073541247025 76.9834949885766 0]);

% Create plot
plot(X1,Y1,'DisplayName','Теория','HitTest','off','LineWidth',10,...
    'Color',[0.92156862745098 0.396078431372549 0.317647058823529 0.8]);

% Create ylabel
ylabel('$$P$$','FontName','Times New Roman','Interpreter','latex');

% Create xlabel
xlabel('$$1-F$$','FontName','Times New Roman','Interpreter','latex');

% Create title
title('Протокол тетраэдра','FontSize',20,'FontName','Times New Roman');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.913725490196078 0.862745098039216 0.788235294117647],...
    'FontSize',14);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.717850287907869 0.740972617851471 0.174504153379996 0.138061649871595],...
    'FontSize',14,...
    'EdgeColor',[0.666666666666667 0.666666666666667 0.658823529411765],...
    'Color',[0.666666666666667 0.666666666666667 0.658823529411765]);

